#!/bin/sh
# Runs after packages are installed and the overlay is copied,
# right before the root filesystem image is created.
# Buildroot passes the target directory as $1.
#
# Secrets are never stored in the repository. They come from the
# environment of the "make" call (see secrets.env.example):
#   ROOT_PASSWORD_HASH  crypt hash for root, e.g. from "mkpasswd -m sha-512"
#   WIFI_SSID           Wi-Fi network name
#   WIFI_PASSWORD       Wi-Fi passphrase (PSK is derived here), or
#   WIFI_PSK            precomputed 64-hex-digit PSK instead of the passphrase
#   WIFI_COUNTRY        regulatory domain, optional (default: UA)
set -eu

TARGET_DIR="$1"

die() {
	echo "post-build: $*" >&2
	exit 1
}

# --- Root password --------------------------------------------------------
# Buildroot has already written /etc/shadow (with an empty root password,
# because BR2_TARGET_GENERIC_ROOT_PASSWD is empty); replace the hash here.
: "${ROOT_PASSWORD_HASH:?is not set, see secrets.env.example}"
case "$ROOT_PASSWORD_HASH" in
	'$5$'*|'$6$'*) ;;
	*) die "ROOT_PASSWORD_HASH must be a SHA-256/SHA-512 crypt hash (\$5\$... or \$6\$...)" ;;
esac
# '|' as sed delimiter: crypt hashes may contain '/' but never '|'
sed -i "s|^root:[^:]*:|root:${ROOT_PASSWORD_HASH}:|" "${TARGET_DIR}/etc/shadow"

# --- Wi-Fi ----------------------------------------------------------------
: "${WIFI_SSID:?is not set, see secrets.env.example}"
if [ -z "${WIFI_PSK:-}" ]; then
	: "${WIFI_PASSWORD:?is not set (or set WIFI_PSK), see secrets.env.example}"
	# WPA2-PSK key: PBKDF2-HMAC-SHA1(passphrase, salt=SSID, 4096 rounds, 32 bytes).
	# Values are passed through the environment, not argv, so they do not show up in ps.
	WIFI_PSK=$(python3 -c 'import hashlib, os; print(hashlib.pbkdf2_hmac("sha1", os.environ["WIFI_PASSWORD"].encode(), os.environ["WIFI_SSID"].encode(), 4096, 32).hex())')
fi
echo "$WIFI_PSK" | grep -qE '^[0-9a-fA-F]{64}$' || die "WIFI_PSK must be 64 hex digits"

# SSID is written hex-encoded, so any characters (quotes, spaces, UTF-8) are safe
WIFI_SSID_HEX=$(printf '%s' "$WIFI_SSID" | od -An -tx1 | tr -d ' \n')

umask 077
cat > "${TARGET_DIR}/etc/wpa_supplicant.conf" <<EOF
# Generated by post-build.sh from environment variables
ctrl_interface=/var/run/wpa_supplicant
update_config=1
country=${WIFI_COUNTRY:-UA}

network={
    ssid=${WIFI_SSID_HEX}
    psk=${WIFI_PSK}
    key_mgmt=WPA-PSK
}
EOF

# --- Permissions ----------------------------------------------------------
# Dropbear refuses keys if ~/.ssh or authorized_keys are group/world accessible
chmod 700 "${TARGET_DIR}/root/.ssh"
chmod 600 "${TARGET_DIR}/root/.ssh/authorized_keys"

# Wi-Fi credentials should be readable by root only
chmod 600 "${TARGET_DIR}/etc/wpa_supplicant.conf"

# Init scripts must be executable, otherwise rcS skips them
chmod 755 "${TARGET_DIR}/etc/init.d/S99netdiag"
